### ISSUE TITLE
Print kubectl context info when listing clusters or showing cluster details

### ISSUE THREAD

**Issue by marians** [giantswarm/gsctl#281]
### User story

As a user, I want to be aware which clusters I have kubeconfig contexts for, so that I can quickly switch to the correct context to work with a cluster.

### Current situation

Users would have to use `kubectl config get-contexts` to list all contexts, trying to recognize the context names or, if they contain the cluster ID, match them with the cluster ID they are interested in.

### Solutions

How about adding a `CONTEXT` column to the output of `gsctl list clusters` which shows, if available, the names(s) of the context(s) for the cluster?

```nohighlight
ID     ORGANIZATION       NAME                  RELEASE  CREATED                 CONTEXT
54k5t  acme               acmeDev2              1.0.0    2018 Jun 22, 13:16 UTC  n/a
6cs7a  acme               acmeProd              1.0.0    2018 Jun 22, 19:14 UTC  n/a
6iec4  giantswarm         Giant Swarm Frontend  1.0.0    2018 Jul 19, 14:09 UTC  frontend
vbbd2  giantswarm         Test cluster          1.0.0    2018 Jul 06, 12:54 UTC  n/a
ye5vx  msft-german-cloud  Test cluster          1.0.0    2018 Jul 30, 11:28 UTC  msft,msft-admin
```

As the relationship between cluster and contexts is potentially `1:n`, the above solution would only work well for cases where there are very few contexts per cluster, and they should have very short names. This calls for a default limit up to which we show the complete list, and a truncation mechanism (which could be deactivated with a `--full` switch, like in `gsctl list keypairs`).

As an alternative, we could change the `gsctl show cluster` output to list all contexts. Example:

```nohighlight
ID:                            6iec4
Name:                          Giant Swarm Frontend
Created:                       2018 Jul 19, 14:09 UTC
Organization:                  giantswarm
Kubernetes API endpoint:       https://api.6iec4.k8s.codename.westeurope.azure.gigantic.io
Release version:               1.0.0
Workers:                       5
Worker VM size:                Standard_A2_v2
CPU cores in workers:          10
RAM in worker nodes (GB):      21.47
Storage in worker nodes (GB):  107.37
Kubectl contexts:              frontend (current context)
```

The example could be extended to fit more than only one context name easily. The `(current context)` modifier would be shown to let the user know that the named one is the currently selected kubeconfig context.

**Comment by webwurst** [comment]
I dislike this context feature of `kubectl` in general. There is no easy way to [merge multiple configs](https://github.com/kubernetes/kubernetes/issues/46381), also if you regularly create and delete clusters for testing your config gets bloated and it is tedious to clean this up. That's why I work with separate config files for each cluster:

```
# fish-shell
set KUBECONFIG "$HOME/.kube/config.d/$installation-$cluster-system-masters.config"

gsctl create kubeconfig \
  --ttl 7d \
  --certificate-organizations "system:masters" \
  --cluster "$cluster" \
  --description "tobias@giantswarm.io" \
  --self-contained "$KUBECONFIG"
```
This way `ls "$HOME/.kube/config.d/" -1` gives me a nice overview of installations and clusters. But I basically just set `KUBECONFIG` like above whenever I want to reach a cluster. In case `kubectl` complains because the file is missing I create it with `gsctl` and can continue.

For people working with `context` your proposal looks good to me. Question is if this is a bit of over engineering or rather how many customers would use that.

Maybe having separate files in some `config.d/` could also be an interesting feature for customers?

**Comment by ChristianWeissCG** [comment]
I dislike the idea to add "context" columns/rows to the output of ```gsctl``` because of the 1:n relation. As gsctl is not dealing with the context stuff in general, there is only a small config generator build-in command line option to help users - it is only used to generate configs for ```kubectl``` - ```kubectl```is the tool that deals with contexts.

At the moment i use for example:
```gsctl create kubeconfig --certificate-organizations system:masters --cluster abc123 --context PROD ``` to get a named context for ```kubectl```. 

```
$ kubectl config get-contexts
CURRENT   NAME       CLUSTER            AUTHINFO                NAMESPACE
          DEV        giantswarm-abc124   giantswarm-abc124-user   
          DEVOPS     giantswarm-abc126   giantswarm-abc126-user   
          E2E        giantswarm-abc127   giantswarm-abc127-user   
          PREPROD    giantswarm-abc128   giantswarm-abc128-user   
*         PROD       giantswarm-abc123   giantswarm-abc123-user   
          SIT        giantswarm-abc125   giantswarm-abc125-user   
          minikube   minikube           minikube     
```

This makes using ```kubectl config use-context PROD```possible.

I suggest to introduce a unique "cluster short name" when creating the cluster and print the short name next to the ```ÌD``` column in ```gsctl```outputs. 

```gsctl``` should use the "cluster short name" as default for ```--context```when this switch was omitted. Optional it should be possible to use the short name (variable) as prefix in the command line parameter value: ```--context "#shortname#_as_master"```. Result: ```PROD``` or ```PROD_as_master```

**Comment by axbarsan** [comment]
@marians 
Since we now have [a kubectl plugin](https://github.com/giantswarm/kubectl-gs), is this kubectl-specific functionality still needed?
