### ISSUE TITLE
"create cluster" should wait until cluster API is accessible, show indicator

### ISSUE THREAD

**Issue by marians** [giantswarm/gsctl#82]
Currently the `create cluster` command finishes fast, and it suggests to the user to test the new cluster using `kubectl cluster-info`. With the current creation time for a cluster, this is likely to end in this result:

```nohighlight
$ kubectl cluster-info
Unable to connect to the server: EOF
```

To allow for a better experience, we should (by default) check for the cluster to become available, at least for a limited time (e. g. one minute).

User may want to avoid this behaviour, and return quickly. We could support that by adding an optional switch like `--no-wait`.

**Comment by JosephSalisbury** [comment]
As an fyi, it takes about 5-10 minutes for a cluster to come up.

**Comment by marians** [comment]
There is an issue regarding the backend topic: https://github.com/giantswarm/giantswarm/issues/1585

**Comment by marians** [comment]
This relies on the API delivering status update, which is a story we have on the roadmap.

**Comment by axbarsan** [comment]
Do we still want this, @marians?

**Comment by marians** [comment]
Not urgently. While it is still roughly valid from the UX side, it might never land during the lifetime of gsctl.

Current issues

- Waiting until the cluster is fully created (condition "Created" appears) is simplistic and would mean that users wait for a long, long time.
- We are lacking ways to find out that particular functions of the cluster created are already available. For example, how can we determine that the PKI is available and key pairs can be created? Or that the K8s API is available?

My UX vision was that we show several milestones to be reached during creation, and then check them one by one. However this needs proper API support.

**Comment by pipo02mix** [comment]
IMO for now, we can expose the latest status of the cluster in the `gsctl show cluster`. Once our operator  expose more details (events or conditions we will have this for free)

**Comment by axbarsan** [comment]
> * Waiting until the cluster is fully created (condition "Created" appears) is simplistic and would mean that users wait for a long, long time.

Hard to believe anyone would keep a command going 30-40 minutes just so they can see it finish 😅 

> * We are lacking ways to find out that particular functions of the cluster created are already available. For example, how can we determine that the PKI is available and key pairs can be created? Or that the K8s API is available?

This is not impossible, checking if PKI is available is [supported by cluster-service](https://github.com/giantswarm/cluster-service/blob/a412e5ac573bdf58d5fc76e93ee1c2af4a328178/service/keypair/creator/service.go#L107), but we might need a separate request. As for the K8s API, we get the K8s API URL as a response to the cluster creation request. Would a ping to that URL be enough to know if the API is alright?

> My UX vision was that we show several milestones to be reached during creation, and then check them one by one. However this needs proper API support.

I really like this. But I'm not sure if it's worth adding such cool features to `gsctl`, since we try to promote `kubectl-gs` usage

**Comment by tfussell** [comment]
We had to implement this functionality in our Prow helper tool called `standup`. `standup wait` continually checks for the API to be responding, nodes to be ready, and CoreDNS before we run conformance tests. See https://github.com/giantswarm/standup/blob/master/cmd/wait/runner.go#L76 It would be cool to standardize what it means for a cluster to be ready (probably provider-specific since we need, for example, `external-dns` on AWS) and move this code to a common tool like `gsctl` or `kubectl-gs`.

**Comment by marians** [comment]
Since gsctl won't be developed further as we are moving into Management API, I'm closing this issue.
